### PR TITLE
fix: remove hard coded $, use ISO code instead

### PR DESCRIPTION
**Pull request by kyranjamie**
Use ISO currency code, rather than a hard-coded dollar sign. Welcome to Europe 🇪🇺 .

### CODE REVIEW

**Comment by markmhx** [comment]
The position and spacing of the currency code depends on the country, so that may variability probably needs to be factored into this change: https://fastspring.com/blog/how-to-format-30-currencies-from-countries-all-over-the-world/

**Comment by kyranjamie** [comment]
This change aims to fix an incorrect value and follow the [`ISO 4217 standard`](https://en.wikipedia.org/wiki/ISO_4217). For a developer tool, consistency > localisation.

**Review by skylarmb — APPROVED** [review]

**Comment by skylarmb** [comment]
this is outdated. The frontend for this repo was switched out for a react app

**Comment by skylarmb** [comment]
I have added a ticket to our internal tracker to add this same fix to the new React frontend

**Pull request closed without merging**
