### PR TITLE
GatesWang Push

### PR DESCRIPTION
**Pull request by MinSunYou**

### CODE REVIEW

**Comment by MinSunYou** [comment]
Nice

**Comment by MinSunYou** [comment]
Nicee

**Review by GatesWang — COMMENTED** [review]
ok

**Review by GatesWang — APPROVED** [review]
nice

**Comment by jamesrperkins** [comment]
Hi @MinSunYou and @GatesWang you have opened a merge request against our Quickstart repository. 

Please note that you have exposed your `client_id` and `secret` which could be used in a malicious fashion. Your `secret` should not be shared with anyone including Plaid or Plaid Support. We would advise rotating the secret through your Plaid Dashboard using the link below. 

https://dashboard.plaid.com/team/keys 

Cheers.

**Pull request closed without merging**
