### PR TITLE
For Review Only -- Do Not Merge -- VanillaJS OAuth Signin

### PR DESCRIPTION
**Pull request by ToddKerpelman**
So, I think this is what my "Vanilla JS Sign-in" sample app is going to look like at the end of my screencast. It's not really what I'd recommend for a finished app, more like what I would put together so you can see everything in very plain detail. It's made up of three separate pages:

index.html / app.js -- Our initial page to start Link (and also deal with the pop-up situation)
post-oauth.html / post-oauth.js -- Where we redirect people after going through OAuth
access-granted.html / access-granted.html -- Our page for when we have an access token and can make calls on behalf of the user

I just want somebody to double check that this makes sense before I start writing out the script in detail.

If this were a real app, I'd probably go back and combine index.html and post-oauth.html (like we typically do in our quickstart). I might add that in to the end of the video, or just leave that as an exercise for the reader, depending on time.

### CODE REVIEW

**Comment by phoenixy1** [comment]
makes sense to me, anyway! That said, what is supposed to go on your OAuth redirect page is one of the most confusing parts of the process to me personally, so I think combining them in the app at the end of the video might be worth it

**Comment by ToddKerpelman** [comment]
Decided to refactor this a bit to look more like a real-life example, where the index.html page will either send you to a "Connect with Plaid" page, or perform the actual calls, depending on if you're connected or not.

**Comment by lindawoo-plaid** [comment]
I'm not understanding the purpose of the forcePopup.  Is there a case where people would prefer a popup?  Otherwise this looks fine to me.

**Comment by lindawoo-plaid** [comment]
This looks fine to me, but is the isPop up necessary?

**Pull request closed without merging**
